# Generated by Django 2.2 on 2021-12-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='fotos')),
                ('foto2', models.ImageField(blank=True, upload_to='fotos')),
                ('foto3', models.ImageField(blank=True, upload_to='fotos')),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('contato', models.CharField(max_length=20)),
                ('contato2', models.CharField(blank=True, max_length=20)),
                ('valor', models.IntegerField()),
                ('data', models.CharField(blank=True, max_length=8)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.CategoriaItem')),
            ],
        ),
    ]
