# Generated by Django 2.2 on 2021-12-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_item_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='foto2',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='foto3',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
