# Generated by Django 4.0 on 2021-12-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0009_alter_item_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='valor',
            field=models.IntegerField(max_length=20),
        ),
    ]
