# Generated by Django 4.0 on 2021-12-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0010_alter_item_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='valor',
            field=models.CharField(max_length=100),
        ),
    ]
